# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Description: |
  account-bootstrap-shared-product and account-creation-shared-product must both be provisioned into the same accountbefore this will work - they build some resources needed for this to work and they provision the SSM params with thecorrect ARNs so this works with no copy and pasting.Provisioning this template will create an AWS Account and bootstrap it using aws-service-catalog-puppet so you canprovision products into the account.
  {"framework": "servicecatalog-products", "role": "product", "product-set": "governance-at-scale-account-factory", "product": "aws-service-catalog-account-creation", "version": "v1"}

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Account Details
        Parameters:
          - AccountName
          - Email
          - AccountGroup
          - AccountType
          - OrganizationAccountAccessRole
          - IamUserAccessToBilling
      - Label:
          default: Lambda ARNs
        Parameters:
          - GovernanceAtScaleAccountFactoryAccountCreationCRArn
          - GovernanceAtScaleAccountFactoryAccountCreateUpdateNotifierCRArn
          - GovernanceAtScaleAccountFactoryAccountTypeToOUChooserCRArn
          - GovernanceAtScaleAccountFactoryMoveToOUArn
          - GovernanceAtScaleAccountFactoryAccountWaiterArn
          - GovernanceAtScaleAccountFactoryBootstrapperProjectCustomResourceArn
      - Label: 
          default: Service Catalog Puppet
        Parameters:
          - ServiceCatalogPuppetVersion
    ParameterLabels:
      AccountName:
        default: Account Name
      Email:
        default: Account Email Address
      AccountGroup:
        default: Account Group
      AccountType:
        default: Account Type
      IamUserAccessToBilling: 
        default: User Access to Billing
      OrganizationAccountAccessRole:
        default: Organization Account Access IAM Role Name
      GovernanceAtScaleAccountFactoryAccountCreationCRArn:
        default: Account Creation Lambda ARN
      GovernanceAtScaleAccountFactoryAccountCreateUpdateNotifierCRArn:
        default: Account Notifier ARN
      GovernanceAtScaleAccountFactoryAccountTypeToOUChooserCRArn:
        default: Account Type to OU Lambda ARN
      GovernanceAtScaleAccountFactoryMoveToOUArn:
        default: Move to OU Lambda ARN
      GovernanceAtScaleAccountFactoryAccountWaiterArn:
        default: Account Waiter Lambda ARN
      GovernanceAtScaleAccountFactoryBootstrapperProjectCustomResourceArn:
        default: Bootstraper Lambda ARN
      ServiceCatalogPuppetVersion:
        default: Service Catalog Puppet Version

Parameters:
  Email:
    Type: String
    Description: The email address to use for the account that is to be created
  AccountName:
    Type: String
    Description: The name to use for the account that is to be created
  OrganizationAccountAccessRole:
    Type: String
    Default: OrganizationAccountAccessRole
    Description: The name of the role to be created in the account that allows Organizations access
  IamUserAccessToBilling:
    Type: String
    Default: "ALLOW"
    AllowedValues: ['ALLOW', 'DENY']
  AccountGroup:
    Type: String
    Description: >-
      Which platform does the account belong to
    AllowedValues:
      - Security
      - Infrastructure
      - Workload
  AccountType:
    Type: String
    Description: >-
      Which stage of the SDLC is the account going to be used for
    AllowedValues:
      - dev
      - test
      - preprod
      - prod
  GovernanceAtScaleAccountFactoryAccountCreationCRArn:
    Type: String
    Description: The ARN of the account creation lambda
  GovernanceAtScaleAccountFactoryMoveToOUArn:
    Type: String
    Description: The ARN of the move to ou lambda
  GovernanceAtScaleAccountFactoryAccountWaiterArn:
    Type: String
    Description: The ARN of the move to ou lambda
  GovernanceAtScaleAccountFactoryBootstrapperProjectCustomResourceArn:
    Type: String
    Description: The ARN of the account bootstrapping lambda
  GovernanceAtScaleAccountFactoryAccountTypeToOUChooserCRArn:
    Type: String
    Description: The ARN of the lambda that converts group and type to Arn
  GovernanceAtScaleAccountFactoryAccountCreateUpdateNotifierCRArn:
    Type: String
    Description: The ARN of the lambda that will dispatch SNS notifications on account creation / update
  ServiceCatalogPuppetVersion:
    Type: String
    Description: The version of Service Catalog Puppet in use

Resources:
  OUDetails:
    Type: Custom::Resource
    DeletionPolicy: Retain
    Description: | 
      A custom resource using the GovernanceAtScaleAccountFactoryAccountTypeToOUChooserCRArn 
      AWS Lambda function to convert the account type and group into the correct 
      organizational unit (OU)
    Properties:
      ServiceToken: !Ref GovernanceAtScaleAccountFactoryAccountTypeToOUChooserCRArn
      AccountType: !Ref AccountType
      AccountGroup: !Ref AccountGroup
      AccountPartition: Commercial

  Account:
    Type: Custom::Resource
    Description: | 
      A custom resource using the GovernanceAtScaleAccountFactoryAccountCreationCRArn 
      AWS Lambda function to create the new account
    Properties:
      ServiceToken: !Ref GovernanceAtScaleAccountFactoryAccountCreationCRArn
      Email: !Ref Email
      AccountName: !Ref AccountName
      IamUserAccessToBilling: !Ref IamUserAccessToBilling

  MoveToOU:
    Type: Custom::Resource
    Description: | 
      A custom resource using the GovernanceAtScaleAccountFactoryMoveToOUArn 
      AWS Lambda function to move the new account to the correct OU
    Properties:
      ServiceToken: !Ref GovernanceAtScaleAccountFactoryMoveToOUArn
      AccountType: !Ref AccountType
      AccountGroup: !Ref AccountGroup
      TargetOU: !GetAtt OUDetails.OrganizationalUnitName
      AccountId: !GetAtt Account.account_id

  AccountWaiterConditionHandle1:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}

  AccountWaiter1:
    Type: Custom::Resource
    Description: | 
      A custom resource using the GovernanceAtScaleAccountFactoryAccountWaiterArn 
      AWS Lambda function to wait for CodeBuild and CloudFormation to become 
      available in the new account
    Properties:
      ServiceToken: !Ref GovernanceAtScaleAccountFactoryAccountWaiterArn
      AccountId: !GetAtt Account.account_id
      ServiceCatalogPuppetVersion: !Ref ServiceCatalogPuppetVersion
      Handle: !Ref AccountWaiterConditionHandle1
      AccountPartition: aws

  AccountWaiterCondition1:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: AccountWaiter1
    Properties:
      Handle: !Ref AccountWaiterConditionHandle1
      Timeout: 28800

  Notifier:
    Type: Custom::Resource
    DeletionPolicy: Retain
    Description: | 
      A custom resource using the GovernanceAtScaleAccountFactoryAccountCreateUpdateNotifierCRArn 
      AWS Lambda function to send a notification when the new account is created
    Properties:
      ServiceToken: !Ref GovernanceAtScaleAccountFactoryAccountCreateUpdateNotifierCRArn
      AccountName: !Ref AccountName
      AccountEmail: !Ref Email
      ManagedOrganizationalUnit: !GetAtt OUDetails.OrganizationalUnitName
      AccountId: !GetAtt Account.account_id
      AccountPartition: Commercial

  AccountBootstrapConditionHandle1:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}

  Bootstrap:
    Type: Custom::CustomResource
    DependsOn: AccountWaiter1
    Description: |
      A custom resource using the GovernanceAtScaleAccountFactoryBootstrapperProjectCustomResourceArn 
      AWS Lambda function to bootstrap the new account
    Properties:
      ServiceToken: !Ref GovernanceAtScaleAccountFactoryBootstrapperProjectCustomResourceArn
      OrganizationAccountAccessRoleName: !Ref OrganizationAccountAccessRole
      TargetAccountId: !GetAtt Account.account_id
      PuppetAccountId: !Sub "${AWS::AccountId}"
      Handle: !Ref AccountBootstrapConditionHandle1
      AccountPartition: aws

  AccountBootstrapCondition1:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: Bootstrap
    Properties:
      Handle: !Ref AccountBootstrapConditionHandle1
      Timeout: 28800

Outputs:
  AccountId:
    Description: The ID of the new account
    Value: !GetAtt Account.account_id