AWSTemplateFormatVersion: '2010-09-09'
Description: |
    Builds out a public subnet for use

Parameters:
  VPCId:
    Type: String
    Description: |
      VPC to create the subnet in

  PublicSubnetCIDR:
    Type: String
    Default: '10.0.0.0/16'
    Description: |
      CIDR to use for the Public Subnet

Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Description: The public subnet that is created
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: {Ref: 'AWS::Region'}
      VpcId: !Ref VPCId
      CidrBlock: !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Description: The internet gateway to attach to the public subnet

  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Description: Attach the gateway to the subnet
    Properties:
      VpcId: !Ref VPCId
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Description: Associate the route table for the subnet
    Properties:
      VpcId: !Ref VPCId

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachement
    Description: Set up the route out to the internet
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Description: Associate the route
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

Outputs:
  PublicSubnetId:
    Description: The subnet id of the public subnet created
    Value: !Ref PublicSubnet
