# Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  {"framework": "servicecatalog-products", "role": "product", "product-set": "account-vending", "product": "prereqs-orgs-account", "version": "v1"}


Parameters:
  SCTAccountId:
    Type: String

  AccountVendingOrgsRoleName:
    Type: String
    Default: AccountVendingOrgsRole

  AccountVendingIAMRolesPath:
    Type: String
    Default: /foundational/account-vending/


Resources:
  AccountVendingOrgsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AccountVendingOrgsRoleName
      Path: !Ref AccountVendingIAMRolesPath
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${SCTAccountId}:root"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: PermissionsNeededForOrgs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - organizations:CreateAccount
                  - organizations:DescribeCreateAccountStatus
                  - organizations:ListAccounts
                  - organizations:ListAccountsForParent
                  - organizations:MoveAccount
                  - organizations:ListParents
                Resource: "*"

Outputs:
  AccountVendingOrgsRoleArn:
    Description: Arn of the AccountVendingOrgsRole
    Value: !GetAtt AccountVendingOrgsRole.Arn