# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates a Lambda-backed custom resource which will assume a role in the hub account and register itself

Parameters:
    HubEnablerFunctionRole:
      Type: String
      Description: ARN of the GuardDuty role in the hub that GuardDutyRegisterFunction will assume into
    GuardDutyAssumableOrgRoleArn:
      Type: String
      Description: ARN of the Organizations role in the root that GuardDutyRegisterFunction will assume into
    HubAccountID:
      Type: String
      Description: The AccountID of the guardduty hub account


Resources:
  GuardDutyRegisterFunction:
    Type: AWS::Serverless::Function
    Description: |
      A lambda function that will find/create guardduty detector then register itself in the hub and send an invite
    Properties:
      Runtime: python3.7
      Handler: lambda_handler.handler
      CodeUri: ./src
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: !Ref HubEnablerFunctionRole
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: !Ref GuardDutyAssumableOrgRoleArn
            - Effect: Allow
              Action:
                - guardduty:AcceptInvitation
                - guardduty:ListDetectors
                - guardduty:CreateDetector
                - guardduty:ListInvitations
                - guardduty:DisassociateFromMasterAccount
                - guardduty:DeleteInvitations
                - iam:CreateServiceLinkedRole
              Resource: "*"
      Timeout: 900

  SpokeCustomResource:
    Type: Custom::RegisterGuardDuty
    Properties:
      ServiceToken: !GetAtt GuardDutyRegisterFunction.Arn
      AssumableHubRoleArn: !Ref HubEnablerFunctionRole
      SpokeAccountID: !Ref AWS::AccountId
      GuardDutyAssumableOrgRoleArn: !Ref GuardDutyAssumableOrgRoleArn
      HubAccountId: !Ref HubAccountID
