# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates an AWS CloudTrail trail and an Amazon S3 bucket where logs are published.
  You can optionally change the behaviour:
    - which encryption to use for your buckets
    - whether CloudTrail validates the integrity of the log files
    - whether the trail is publishing events from global services, such as IAM, to the log files
    - whether the CloudTrail trail is created in the region in which you create the stack or in all regions

Parameters:
  EnableLogFileValidation:
    Type: String
    Default: 'true'
    Description: Indicates whether CloudTrail validates the integrity of log files
    AllowedValues:
      - 'true'
      - 'false'

  IncludeGlobalEvents:
    Type: String
    Default: 'true'
    Description: Indicates whether the trail is publishing events from global services, such as IAM, to the log files.
    AllowedValues:
      - 'true'
      - 'false'

  MultiRegion:
    Type: String
    Default: 'false'
    Description: |
      Indicates whether the CloudTrail trail is created in the region in which you create the stack (false) or in all
      regions (true).
    AllowedValues:
      - 'true'
      - 'false'

  TrailBucket:
    Type: String
    Description: Bucket name for logs.

  LoggingAccountID:
    Type: String
    Description: |
      This is the account where the S3 buckets should be stored. If this is the account where the template is deployed
      the bucket will be created

  SSEAlgorithm:
    Type: 'String'
    Default: 'AES256'
    Description: Which S3 bucket SSE Algorithm to use when creating the logging bucket.
    AllowedValues:
    - 'AES256'
    - 'aws:kms'

  KMSMasterKeyID:
    Type: 'String'
    Description: 'KMS key ID to use when SSE algorithm is aws:kms.'

Conditions:
  UseKMS: !Equals
    - !Ref SSEAlgorithm
    - 'aws:kms'
  UseAES256: !Equals
    - !Ref SSEAlgorithm
    - 'AES256'
  AccountMatch: !Equals
    - !Ref AWS::AccountId
    - !Ref LoggingAccountID
  KMSDeploy: !And
    - !Condition AccountMatch
    - !Condition UseKMS
  AES256Deploy: !And
    - !Condition AccountMatch
    - !Condition UseAES256
  SpokeDeploy:
    !Not [Condition: AccountMatch]

Resources:
  KMSTrail:
    Condition: KMSDeploy
    Description: CloudTrail trail to use when KMS encryption is used
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref TrailBucket
      IsLogging: True
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion
    DependsOn:
      - S3KmsBucket
      - S3KmsBucketPolicy

  AES256Trail:
    Condition: AES256Deploy
    Description: CloudTrail trail to use when AES256 encryption is used
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref TrailBucket
      IsLogging: True
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion
    DependsOn:
      - S3Bucket
      - S3BucketPolicy

  SpokeTrail:
    Condition: SpokeDeploy
    Type: AWS::CloudTrail::Trail
    Description: CloudTrail trail to use when deploying into a spoke account
    Properties:
      S3BucketName: !Ref TrailBucket
      IsLogging: True
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion

  S3KmsLoggingBucket:
    DeletionPolicy: Retain
    Condition: KMSDeploy
    Description: S3 bucket to use for logging the logging bucket when KMS encryption is used
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub centralised-cloudtrail-s3-access-logs-${AWS::AccountId}-${AWS::Region}
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref KMSMasterKeyID
              SSEAlgorithm: !Ref SSEAlgorithm

  S3KmsBucket:
    DeletionPolicy: Retain
    Condition: KMSDeploy
    Description: S3 bucket to use when KMS encryption is used for logging
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TrailBucket
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref S3KmsLoggingBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref KMSMasterKeyID
              SSEAlgorithm: !Ref SSEAlgorithm

  S3KmsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: KMSDeploy
    Description: S3 bucket policy to use when KMS encryption is used for logging
    Properties:
      Bucket: !Ref S3KmsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}"
          - Sid: AWSBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource:
                    - Fn::Join:
                        - ""
                        -
                          - "arn:aws:s3:::"
                          - !Ref "S3Bucket"
                          - "/AWSLogs/*/*"

  # Create buckets using S3-SSE keys for default encryption
  S3LoggingBucket:
    DeletionPolicy: Retain
    Condition: AES256Deploy
    Description: S3 bucket to use for logging the logging bucket when AES256 encryption is used
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub centralised-cloudtrail-s3-access-logs-${AWS::AccountId}-${AWS::Region}
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref SSEAlgorithm

  S3Bucket:
    DeletionPolicy: Retain
    Description: S3 bucket to use when KMS encryption is used for logging
    Condition: AES256Deploy
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TrailBucket
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LoggingBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref SSEAlgorithm

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Description: S3 bucket policy to use when AES256 encryption is used for logging
    Condition: AES256Deploy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
                - config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}"
          - Sid: AWSBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
                - config.amazonaws.com
            Action: s3:PutObject
            Resource:
                    - Fn::Join:
                        - ""
                        -
                          - "arn:aws:s3:::"
                          - !Ref "S3Bucket"
                          - "/AWSLogs/*/*"
          - Sid: AWSBucketRead
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: s3:GetObject
            Resource:
                    - Fn::Join:
                        - ""
                        -
                          - "arn:aws:s3:::"
                          - !Ref "S3Bucket"
                          - "/AWSLogs/*/*"
