AWSTemplateFormatVersion: '2010-09-09'
Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html
Parameters:
  PeerOwnerId:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html#cfn-ec2-vpcpeeringconnection-peerownerid
    Default: null
  PeerRegion:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html#cfn-ec2-vpcpeeringconnection-peerregion
    Default: null
  PeerRoleArn:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html#cfn-ec2-vpcpeeringconnection-peerrolearn
    Default: null
  PeerVpcId:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html#cfn-ec2-vpcpeeringconnection-peervpcid
  VpcId:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html#cfn-ec2-vpcpeeringconnection-vpcid
Resources:
  Resource:
    Type: AWS::EC2::VPCPeeringConnection
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html
    Properties:
      PeerOwnerId: !Ref 'PeerOwnerId'
      PeerRegion: !Ref 'PeerRegion'
      PeerRoleArn: !Ref 'PeerRoleArn'
      PeerVpcId: !Ref 'PeerVpcId'
      VpcId: !Ref 'VpcId'
