AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Builds out a VPC for use

Parameters:
  VPCCIDR:
    Type: String
    Default: '10.0.0.0/16'
    Description: |
      Subnet to use for the VPC

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Description: The vpc being created
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref VPCCIDR

Outputs:
  VPCId:
    Description: The ID of the VPC that was created
    Value: !Ref VPC
