# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Creates the datastore needed for governance@scale account management
  {"version": "v1", "framework": "servicecatalog-products", "role": "product", "product-set": "governance-at-scale-account-management", "product": "datastore"}

Resources:
  Account:
    Description: "Storage for the account management apis"
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      VersioningConfiguration:
        Status: Enabled

Outputs:
  GASDataStoreBucketName:
    Description: "The name of the bucket"
    Value: !Ref Account

  GASDataStoreBucketArn:
    Description: "The Arn of the bucket"
    Value: !GetAtt Account.Arn
