# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Takes the given account type and returns the organizational unit it should be assigned to

Resources:
  Function:
    Description: |
      Lambda function to back an AWS CloudFormation custom resource.  This expects a ResourceProperty of AccountType and
      will return an organizational_unit_id based on the dict organizational_unit_ids
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'account-type-to-organizational-unit-id'
      Handler: index.lambda_handler
      Timeout: 3
      Role: !GetAtt Role.Arn
      Runtime: python3.7
      Code:
        ZipFile: |
          import logging
          import cfnresponse

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          DEFAULT_OU_ID = 'ou-root'
          organizational_unit_ids = {
            'dev': 'ou-dev',
            'test': 'ou-test',
            'pre-prod': 'ou-pre-prod',
            'prod': 'ou-prod',
          }

          def lambda_handler(event, context):
            logger.info('got event {}'.format(event))
            response_data = {}

            if event['RequestType'] == 'Create':
              account_type = event['ResourceProperties'].get('AccountType')
              organizational_unit_id = organizational_unit_ids.get(account_type, DEFAULT_OU_ID)
              response_data['OrganizationalUnitId'] = organizational_unit_id

            else: # delete / update
              pass

            logger.info('response_data {}'.format(response_data))
            cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data, response_data['OrganizationalUnitId'])

  Role:
    Type: AWS::IAM::Role
    Description: |
      IAM role needed to execute account-type-to-organizational-unit-id.  Only needs basic access.
    Properties:
      Path: /aws-control-tower-augmented-account-factory/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  AccountTypeToOrganizationalUnitIdCustomResourceArn:
    Description: |
      Outputs the Function Arn so others can use it
    Value: !GetAtt Function.Arn
