# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Creates a CodeStar connection that can be given to CodePipeline so that it can access third-party code repositories. 
  {"framework": "servicecatalog-products", "role": "product", "product-set": "cloud-custodian", "product": "codestar-connection", "version": "v2"}

Parameters:

  ConnectionName:
    Type: String
    Description: The name of the connection

  ProviderType:
    Type: String
    Description: The name of your third-party code repository provider
    Default: "GitHub"
    AllowedValues:
      - GitHub
      - Bitbucket
      - GitHubEnterpriseServer

Resources:
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties: 
      ConnectionName: !Ref ConnectionName
      ProviderType: !Ref ProviderType

Outputs:
  CodeStarConnectionArn:
    Description: The ARN of the CodeStar Connection
    Value: !Ref CodeStarConnection
