# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Augments AWS Control Tower Account Factory - simplifies user input, dispatches extra parameters via AWS SNS and
  returns the account id as an output

Parameters:
  AccountName:
    Description: The AWS Account Name
    Type: String
    AllowedPattern: '[a-zA-Z0-9][a-zA-Z0-9._-]*'
  AccountEmail:
    Description: The account email. This must be unique across AWS and must already exist.
    Type: String
    AllowedPattern: '[^\s@]+@[^\s@]+\.[^\s@]+'
  SSOUserFirstName:
    Description: SSO user first name.
    Type: String
    AllowedPattern: .+
  SSOUserLastName:
    Description: SSO user last name.
    Type: String
    AllowedPattern: .+
  SSOUserEmail:
    Description: >-
      SSO user email. A new SSO user will be created for this email, if it does
      not exist. This SSO user will be associated with the new managed Account.
    Type: String
    AllowedPattern: '[^\s@]+@[^\s@]+\.[^\s@]+'
  AccountType:
    Type: String
    Description: >-
      Which stage of the SDLC is the account going to be used for
    AllowedValues:
      - dev
      - test
      - preprod
      - prod
  PlatformName:
    Type: String
    Description: >-
      Which platform does the account belong to
    AllowedValues:
      - dev
      - test
      - preprod
      - prod

Resources:
  OUDetails:
    Type: Custom::Resource
    DependsOn: TriggerCoreAccountFactory
    Properties:
      ServiceToken:
        !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:account-type-to-organizational-unit-id"
      AccountType: !Ref AccountType
      PlatformName: !Ref PlatformName

  TriggerCoreAccountFactory:
    Type: 'AWS::ServiceCatalog::CloudFormationProvisionedProduct'
    DeletionPolicy: Retain
    Properties:
      ProductName: AWS Control Tower Account Factory
      ProvisioningArtifactName: AWS Control Tower Account Factory
      ProvisionedProductName: !Sub
        - 'Account-${AccountName}'
        - {}
      ProvisioningParameters:
        - Key: AccountName
          Value: !Ref AccountName
        - Key: AccountEmail
          Value: !Ref AccountEmail
        - Key: SSOUserFirstName
          Value: !Ref SSOUserFirstName
        - Key: SSOUserLastName
          Value: !Ref SSOUserLastName
        - Key: SSOUserEmail
          Value: !Ref SSOUserEmail
        - Key: ManagedOrganizationalUnit
          Value: !GetAtt OUDetails.OrganizationalUnitId

  AccountDetails:
    Type: Custom::Resource
    DependsOn: TriggerCoreAccountFactory
    Properties:
      ServiceToken:
        !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:account-details-to-aws-account-id"
      AccountName: !Ref AccountName

  Notifier:
    Type: Custom::Resource
    DependsOn:
      - AccountDetails
      - OUDetails
    Properties:
      ServiceToken:
        !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:account-creation-notifier"
      AccountName: !Ref AccountName
      AccountEmail: !Ref AccountEmail
      SSOUserFirstName: !Ref SSOUserFirstName
      SSOUserLastName: !Ref SSOUserLastName
      SSOUserEmail: !Ref SSOUserEmail
      ManagedOrganizationalUnit: !GetAtt OUDetails.OrganizationalUnitId
      AccountId: !GetAtt AccountDetails.Id

Outputs:
  AccountId:
    Description: |
      AccountId for the newly created AWS Account
    Value: !GetAtt AccountDetails.Id
